version: '2'

services:
  postgres:
    image: postgres:11.4
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=hrrch
      - POSTGRES_USER=hrrch
      - POSTGRES_DB=hrrch
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - ./init_ltree.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    expose:
      - 5432

  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    expose:
      - 27017
